### PR TITLE
update to new switch for puzzle7

### PR DESCRIPTION
**Pull request by ihurrahi**
peek 2019-02-27 22-35

### CODE REVIEW

**Comment by cschois1** [comment]
Could we arrange the switches to be 1-5 on the left side and 6-10 on the right? I've already written the clues to be according to this arrangement I described.

**Comment by cschois1** [comment]
(But if that's challenging, I can try to rewrite the clues.)

**Comment by ihurrahi** [comment]
Not a problem, this is still a work in progress, just wanted to get feedback on it before I worked on it more

**Comment by cschois1** [comment]
Ok cool awesome! I like the switch images/motion.

**Pull request merged**
